//! Stable Knowledge Registry (PRD §12.1.1) and `RegistryRevision`
//! transactional semantics.
//!
//! - IDs are opaque `kn_<ULID>` assigned here — never derived from names,
//!   never generated by the LLM (PRD §12.1.1, §45).
//! - Every committed mutation (create / merge / retire / status change) bumps
//!   the workspace `RegistryRevision` exactly once **in the same
//!   transaction**; a rolled-back transaction never advances it.
//! - Canonical keys are the deterministic-normalization stage of entity
//!   resolution (PRD §13): NFKC + case-fold + trim. The LLM only *suggests*
//!   merges; this module executes them.
//!
//! Security note: every query takes parameters — no string assembly of
//! external input (PRD §42).

use rusqlite::{params, Connection, Transaction};

use llm_wiki_core::error::{Result, WikiError};
use llm_wiki_core::ids::KnowledgeNodeId;

use unicode_normalization::UnicodeNormalization;

pub const REVISION_KEY: &str = "registry_revision";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NodeKind {
    Entity,
    Concept,
    Topic,
    Claim,
}

impl NodeKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            NodeKind::Entity => "entity",
            NodeKind::Concept => "concept",
            NodeKind::Topic => "topic",
            NodeKind::Claim => "claim",
        }
    }

    pub fn parse(s: &str) -> Result<Self> {
        match s {
            "entity" => Ok(NodeKind::Entity),
            "concept" => Ok(NodeKind::Concept),
            "topic" => Ok(NodeKind::Topic),
            "claim" => Ok(NodeKind::Claim),
            other => Err(WikiError::Storage(format!("unknown node kind: {other}"))),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RegistryEntry {
    pub id: KnowledgeNodeId,
    pub node_kind: NodeKind,
    pub canonical_key: String,
    pub canonical_name: Option<String>,
    pub status: String,
    pub merged_into: Option<KnowledgeNodeId>,
    pub created_build_id: Option<String>,
    pub retired_build_id: Option<String>,
    pub created_revision: i64,
}

/// Deterministic stage-1 entity normalization (PRD §13): NFKC (which also
/// folds full/half width), case-fold via lowercase, trim.
pub fn canonical_key(name: &str) -> String {
    let nfkc: String = name.nfkc().collect();
    nfkc.chars()
        .flat_map(char::to_lowercase)
        .collect::<String>()
        .trim()
        .to_owned()
}

pub fn current_revision(conn: &Connection) -> Result<u64> {
    let value: String = conn
        .query_row(
            "SELECT value FROM meta WHERE key = ?1",
            params![REVISION_KEY],
            |row| row.get(0),
        )
        .map_err(|e| WikiError::Storage(format!("cannot read registry revision: {e}")))?;
    value
        .parse()
        .map_err(|e| WikiError::Storage(format!("registry revision is not a number: {e}")))
}

/// Bumps the revision inside the given transaction. Callers must invoke this
/// exactly once per committed mutating transaction.
fn bump_revision(tx: &Transaction) -> Result<u64> {
    tx.execute(
        "UPDATE meta SET value = CAST(CAST(value AS INTEGER) + 1 AS TEXT) WHERE key = ?1",
        params![REVISION_KEY],
    )
    .map_err(|e| WikiError::Storage(format!("cannot bump registry revision: {e}")))?;
    current_revision(tx)
}

fn db(e: rusqlite::Error) -> WikiError {
    WikiError::Storage(e.to_string())
}

fn row_to_entry(row: &rusqlite::Row) -> Result<RegistryEntry> {
    let kind: String = row.get("node_kind").map_err(db)?;
    let merged_into: Option<String> = row.get("merged_into").map_err(db)?;
    Ok(RegistryEntry {
        id: KnowledgeNodeId::from_validated(row.get::<_, String>("id").map_err(db)?),
        node_kind: NodeKind::parse(&kind)?,
        canonical_key: row.get("canonical_key").map_err(db)?,
        canonical_name: row.get("canonical_name").map_err(db)?,
        status: row.get("status").map_err(db)?,
        merged_into: merged_into.map(KnowledgeNodeId::from_validated),
        created_build_id: row.get("created_build_id").map_err(db)?,
        retired_build_id: row.get("retired_build_id").map_err(db)?,
        created_revision: row.get("created_revision").map_err(db)?,
    })
}

const SELECT_ENTRY: &str =
    "SELECT id, node_kind, canonical_key, canonical_name, status, merged_into, created_build_id, retired_build_id, created_revision FROM knowledge_registry WHERE id = ?1";

pub fn get_entry(conn: &Connection, id: &KnowledgeNodeId) -> Result<Option<RegistryEntry>> {
    let mut stmt = conn
        .prepare(SELECT_ENTRY)
        .map_err(|e| WikiError::Storage(format!("prepare get_entry: {e}")))?;
    let mut rows = stmt
        .query(params![id.as_str()])
        .map_err(|e| WikiError::Storage(format!("get_entry: {e}")))?;
    match rows.next() {
        Ok(Some(row)) => Ok(Some(row_to_entry(row)?)),
        Ok(None) => Ok(None),
        Err(e) => Err(WikiError::Storage(format!("get_entry: {e}"))),
    }
}

/// Resolves a canonical key to its current primary node, following
/// `merged_into` chains (bounded to guard against data corruption).
pub fn resolve(conn: &Connection, kind: NodeKind, key: &str) -> Result<Option<KnowledgeNodeId>> {
    let mut stmt = conn
        .prepare(
            "SELECT id, status, merged_into FROM knowledge_registry WHERE node_kind = ?1 AND canonical_key = ?2",
        )
        .map_err(|e| WikiError::Storage(format!("prepare resolve: {e}")))?;
    let mut rows = stmt
        .query(params![kind.as_str(), key])
        .map_err(|e| WikiError::Storage(format!("resolve: {e}")))?;
    let row = match rows.next().map_err(db)? {
        Some(row) => row,
        None => return Ok(None),
    };
    let mut id: String = row.get(0).map_err(db)?;
    let mut status: String = row.get(1).map_err(db)?;
    let mut merged_into: Option<String> = row.get(2).map_err(db)?;

    let mut hops = 0;
    while status == "merged" {
        let target = merged_into.clone().ok_or_else(|| {
            WikiError::Storage(format!("node {id} is merged but has no merged_into target"))
        })?;
        hops += 1;
        if hops > 16 {
            return Err(WikiError::Storage(format!(
                "merged_into chain longer than 16 hops at {id}"
            )));
        }
        let mut stmt = conn
            .prepare("SELECT id, status, merged_into FROM knowledge_registry WHERE id = ?1")
            .map_err(|e| WikiError::Storage(format!("prepare follow merge: {e}")))?;
        let mut rows = stmt
            .query(params![target])
            .map_err(|e| WikiError::Storage(format!("follow merge: {e}")))?;
        match rows.next().map_err(db)? {
            Some(row) => {
                id = row.get(0).map_err(db)?;
                status = row.get(1).map_err(db)?;
                merged_into = row.get(2).map_err(db)?;
            }
            None => {
                return Err(WikiError::Storage(format!(
                    "merged node points to missing target {target}"
                )))
            }
        }
    }
    Ok(Some(KnowledgeNodeId::from_validated(id)))
}

/// Looks up or creates a registry node. Bumps the revision exactly once when
/// (and only when) a node was created; read-only hits never touch it.
pub fn get_or_create(
    conn: &mut Connection,
    kind: NodeKind,
    key: &str,
    canonical_name: &str,
    build_id: Option<&str>,
) -> Result<(KnowledgeNodeId, u64, bool)> {
    if let Some(id) = resolve(conn, kind, key)? {
        let rev = current_revision(conn)?;
        return Ok((id, rev, false));
    }

    let tx = conn
        .transaction()
        .map_err(|e| WikiError::Storage(format!("begin tx: {e}")))?;
    let id = KnowledgeNodeId::generate();
    let rev = current_revision(&tx)? + 1;
    tx.execute(
        "INSERT INTO knowledge_registry (id, node_kind, canonical_key, canonical_name, status, created_build_id, created_revision)
         VALUES (?1, ?2, ?3, ?4, 'active', ?5, ?6)",
        params![id.as_str(), kind.as_str(), key, canonical_name, build_id, rev as i64],
    )
    .map_err(|e| WikiError::Storage(format!("insert registry node: {e}")))?;
    let bumped = bump_revision(&tx)?;
    debug_assert_eq!(bumped, rev);
    tx.commit()
        .map_err(|e| WikiError::Storage(format!("commit create node: {e}")))?;
    Ok((id, rev, true))
}

/// One node to resolve-or-create in a [`get_or_create_batch`] call.
#[derive(Debug, Clone)]
pub struct NodeDraft {
    pub kind: NodeKind,
    pub canonical_key: String,
    pub canonical_name: String,
    /// Entity/concept detail; written for new nodes and refreshed on
    /// existing ones (does not affect resolution, so no revision bump).
    pub entity_type: Option<String>,
    pub description: Option<String>,
}

/// Resolves or creates many nodes inside ONE transaction. The revision is
/// bumped exactly once **per created node** (PRD §12.1.1: every committed
/// node creation increments the revision once); lookups never bump.
/// Returns one id per draft, in input order.
pub fn get_or_create_batch(
    conn: &mut Connection,
    drafts: &[NodeDraft],
    build_id: Option<&str>,
) -> Result<Vec<KnowledgeNodeId>> {
    let tx = conn
        .transaction()
        .map_err(|e| WikiError::Storage(format!("begin tx: {e}")))?;
    let base_revision = current_revision(&tx)?;
    let mut created_count = 0u64;
    let mut ids = Vec::with_capacity(drafts.len());

    {
        let mut select_stmt = tx
            .prepare(
                "SELECT id, status, merged_into FROM knowledge_registry WHERE node_kind = ?1 AND canonical_key = ?2",
            )
            .map_err(db)?;
        let mut insert_stmt = tx
            .prepare(
                "INSERT INTO knowledge_registry (id, node_kind, canonical_key, canonical_name, status, created_build_id, created_revision, entity_type, description)
                 VALUES (?1, ?2, ?3, ?4, 'active', ?5, ?6, ?7, ?8)",
            )
            .map_err(db)?;
        let mut update_detail_stmt = tx
            .prepare(
                "UPDATE knowledge_registry SET entity_type = COALESCE(?1, entity_type), description = COALESCE(?2, description) WHERE id = ?3",
            )
            .map_err(db)?;

        for draft in drafts.iter() {
            let existing: Option<(String, String, Option<String>)> = select_stmt
                .query_row(params![draft.kind.as_str(), draft.canonical_key], |row| {
                    Ok((row.get(0)?, row.get(1)?, row.get(2)?))
                })
                .ok();

            let id = match existing {
                Some((id, status, merged_into)) if status == "merged" => {
                    // Follow the merge chain to the primary node (same tx).
                    let mut current = merged_into.ok_or_else(|| {
                        WikiError::Storage(format!(
                            "node {id} is merged but has no merged_into target"
                        ))
                    })?;
                    loop {
                        let row: Option<(String, String, Option<String>)> = tx
                            .query_row(
                                "SELECT id, status, merged_into FROM knowledge_registry WHERE id = ?1",
                                params![current],
                                |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)),
                            )
                            .ok();
                        match row {
                            Some((id, status, merged_into)) if status == "merged" => {
                                current = merged_into.ok_or_else(|| {
                                    WikiError::Storage(format!(
                                        "node {id} is merged but has no merged_into target"
                                    ))
                                })?;
                            }
                            Some((id, _active, _)) => break KnowledgeNodeId::from_validated(id),
                            None => {
                                return Err(WikiError::Storage(format!(
                                    "merged node points to missing target {current}"
                                )))
                            }
                        }
                    }
                }
                Some((id, _active, _)) => KnowledgeNodeId::from_validated(id),
                None => {
                    created_count += 1;
                    let id = KnowledgeNodeId::generate();
                    insert_stmt
                        .execute(params![
                            id.as_str(),
                            draft.kind.as_str(),
                            draft.canonical_key,
                            draft.canonical_name,
                            build_id,
                            (base_revision + created_count) as i64,
                            draft.entity_type,
                            draft.description
                        ])
                        .map_err(db)?;
                    id
                }
            };

            if draft.entity_type.is_some() || draft.description.is_some() {
                update_detail_stmt
                    .execute(params![draft.entity_type, draft.description, id.as_str()])
                    .map_err(db)?;
            }
            ids.push(id);
        }
    }

    if created_count > 0 {
        // One revision increment per created node, inside the same tx.
        tx.execute(
            "UPDATE meta SET value = CAST(CAST(value AS INTEGER) + ?2 AS TEXT) WHERE key = ?1",
            params![REVISION_KEY, created_count as i64],
        )
        .map_err(db)?;
    }
    tx.commit()
        .map_err(|e| WikiError::Storage(format!("commit batch create: {e}")))?;
    Ok(ids)
}

/// Executes an LLM-confirmed merge: the secondary node becomes `merged` with
/// `merged_into = primary`; the primary keeps its identity and all existing
/// references stay valid (PRD §12.1.1).
pub fn merge(
    conn: &mut Connection,
    primary: &KnowledgeNodeId,
    secondary: &KnowledgeNodeId,
    build_id: Option<&str>,
) -> Result<u64> {
    if primary == secondary {
        return Err(WikiError::Storage(
            "cannot merge a node into itself".to_owned(),
        ));
    }
    let tx = conn
        .transaction()
        .map_err(|e| WikiError::Storage(format!("begin tx: {e}")))?;

    let secondary_entry = get_entry(&tx, secondary)?
        .ok_or_else(|| WikiError::Storage(format!("unknown node {secondary}")))?;
    if secondary_entry.status != "active" {
        return Err(WikiError::Storage(format!(
            "node {secondary} is not active (status {})",
            secondary_entry.status
        )));
    }
    if get_entry(&tx, primary)?.is_none() {
        return Err(WikiError::Storage(format!("unknown node {primary}")));
    }

    tx.execute(
        "UPDATE knowledge_registry SET status = 'merged', merged_into = ?1, retired_build_id = ?2 WHERE id = ?3",
        params![primary.as_str(), build_id, secondary.as_str()],
    )
    .map_err(|e| WikiError::Storage(format!("merge node: {e}")))?;

    let rev = bump_revision(&tx)?;
    tx.commit()
        .map_err(|e| WikiError::Storage(format!("commit merge: {e}")))?;
    Ok(rev)
}

pub fn retire(conn: &mut Connection, id: &KnowledgeNodeId, build_id: Option<&str>) -> Result<u64> {
    let tx = conn
        .transaction()
        .map_err(|e| WikiError::Storage(format!("begin tx: {e}")))?;
    let changed = tx
        .execute(
            "UPDATE knowledge_registry SET status = 'retired', retired_build_id = ?2 WHERE id = ?1 AND status = 'active'",
            params![id.as_str(), build_id],
        )
        .map_err(|e| WikiError::Storage(format!("retire node: {e}")))?;
    if changed == 0 {
        // Retiring a non-active node is a no-op, not a revision bump.
        let rev = current_revision(&tx)?;
        tx.commit()
            .map_err(|e| WikiError::Storage(format!("commit retire: {e}")))?;
        return Ok(rev);
    }
    let rev = bump_revision(&tx)?;
    tx.commit()
        .map_err(|e| WikiError::Storage(format!("commit retire: {e}")))?;
    Ok(rev)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::connection::open_in_memory;

    #[test]
    fn canonical_key_folds_case_width_and_unicode() {
        assert_eq!(
            canonical_key("Plugin Manager"),
            canonical_key("plugin manager")
        );
        assert_eq!(
            canonical_key("PluginManager"),
            canonical_key("pluginmanager")
        );
        assert_eq!(canonical_key("插件管理器"), "插件管理器");
        // Full-width letters fold via NFKC.
        assert_eq!(canonical_key("ＡＰＩ"), canonical_key("api"));
        assert_eq!(canonical_key("  spaced  "), "spaced");
    }

    #[test]
    fn get_or_create_is_idempotent_and_bumps_only_on_create() {
        let mut conn = open_in_memory().unwrap();
        let key = canonical_key("Plugin Manager");

        let (id1, rev1, created1) =
            get_or_create(&mut conn, NodeKind::Entity, &key, "Plugin Manager", None).unwrap();
        assert!(created1);
        assert!(id1.as_str().starts_with("kn_"));
        assert_eq!(rev1, 1);

        let (id2, rev2, created2) =
            get_or_create(&mut conn, NodeKind::Entity, &key, "Plugin Manager", None).unwrap();
        assert!(!created2);
        assert_eq!(id1, id2);
        assert_eq!(rev2, 1, "read-only lookups must not advance the revision");
    }

    #[test]
    fn merge_keeps_primary_and_follows_chain() {
        let mut conn = open_in_memory().unwrap();
        let (primary, _, _) = get_or_create(&mut conn, NodeKind::Entity, "k-a", "A", None).unwrap();
        let (secondary, rev, _) =
            get_or_create(&mut conn, NodeKind::Entity, "k-b", "B", None).unwrap();
        assert_eq!(rev, 2);

        let rev_after = merge(&mut conn, &primary, &secondary, None).unwrap();
        assert_eq!(rev_after, 3);

        // Secondary key now resolves to the primary identity.
        let resolved = resolve(&conn, NodeKind::Entity, "k-b").unwrap().unwrap();
        assert_eq!(resolved, primary);
        let entry = get_entry(&conn, &secondary).unwrap().unwrap();
        assert_eq!(entry.status, "merged");
        assert_eq!(entry.merged_into, Some(primary.clone()));
    }

    #[test]
    fn merge_failure_does_not_advance_revision() {
        let mut conn = open_in_memory().unwrap();
        let (primary, _, _) = get_or_create(&mut conn, NodeKind::Entity, "k-a", "A", None).unwrap();
        let (secondary, _, _) =
            get_or_create(&mut conn, NodeKind::Entity, "k-b", "B", None).unwrap();
        merge(&mut conn, &primary, &secondary, None).unwrap();
        let rev = current_revision(&conn).unwrap();

        // Second merge of the same (now merged) node must fail and must NOT
        // bump the revision — rolled-back transactions never advance it.
        assert!(merge(&mut conn, &primary, &secondary, None).is_err());
        assert_eq!(current_revision(&conn).unwrap(), rev);
    }

    #[test]
    fn retire_is_monotonic_and_noop_safe() {
        let mut conn = open_in_memory().unwrap();
        let (id, _, _) = get_or_create(&mut conn, NodeKind::Concept, "c-1", "C", None).unwrap();

        let rev1 = retire(&mut conn, &id, None).unwrap();
        assert_eq!(rev1, 2);
        let entry = get_entry(&conn, &id).unwrap().unwrap();
        assert_eq!(entry.status, "retired");

        // Retiring again is a no-op without a revision bump.
        let rev2 = retire(&mut conn, &id, None).unwrap();
        assert_eq!(rev2, rev1);
    }
}
